Add readme
CynosuraPlatform/Cynosura.Studio pull request #23
Opened 2019-09-27 01:54 UTC by yamaoto

2019-10-08 06:03 UTC, bacr commented on README.md
> +* MS SQL Server (you can use docker-compose if haven't)
if you don't have it

2019-10-08 06:03 UTC, bacr commented on CONTRIBUTING.md
> +* Use double qout(`"`) for literals
double quotes

2019-10-08 06:03 UTC, bacr commented on CONTRIBUTING.md
> +* Do no use `var`
Do not

2019-10-08 06:03 UTC, bacr commented on CONTRIBUTING.md
> +* Prefer to use Implicit typeing insted Explicit
typing instead

2019-10-08 06:04 UTC, bacr requested changes
Changes requested

2019-12-12 16:48 UTC, yamaoto commented on README.md
> +* MS SQL Server (you can use docker-compose if haven't)
Solved

2019-12-12 16:50 UTC, yamaoto commented on CONTRIBUTING.md
> +* Do no use `var`
Done

2019-12-12 16:50 UTC, yamaoto commented on CONTRIBUTING.md
> +* Prefer to use Implicit typeing insted Explicit
Done

2019-12-17 06:21 UTC, bacr commented on README.md
> +* MS SQL Server (you can use docker-compose if haven't)
Not resolved

2020-05-02 11:29 UTC, bacr approved these changes

2020-05-02 11:57 UTC, merged